### ISSUE TITLE
Build a Responsive Card Grid

### ISSUE THREAD

**Issue by simranlotey** [simranlotey/programs#134]
- Design an HTML structure for a card grid, each containing an image and text.
- Use CSS to create a responsive card grid layout that adapts to different screen sizes.

**Comment by iamrishiksahu** [comment]
I am interested to work on this issue, please assign me this so that I can start working as soon as possible.

**Comment by simranlotey** [comment]
Do it. I assigned you @iamrishiksahu

**Comment by iamrishiksahu** [comment]
Kindly clarify whether I should create a new directory or place it elsewhere.

**Comment by simranlotey** [comment]
Yes, you should create a new directory that contains the directory name of the issue name.

**Comment by iamrishiksahu** [comment]
I have linked the PR, kindly review it.
