### ISSUE TITLE
FizzBuzz

### ISSUE THREAD

**Issue by simranlotey** [simranlotey/programs#225]
Write a program of FizzBuzz in Python, Java, JavaScript, TypeScript, C, Ruby, C++, PHP, Go, Swift, Perl, and Rust.

Note:
1. A contributor should work on only one language.
2. The first contributor should create a new directory that contains the directory name of FizzBuzz and all contributors must enter their code in the FizzBuzz directory.

**Comment by Atheke** [comment]
I would like to work on this issue

**Comment by simranlotey** [comment]
Do it @Atheke

**Comment by avinashyadav16** [comment]
I wish to work on this in python. Can you please assign me too this.

**Comment by ashajyothi06** [comment]
@simranlotey I would like like to work on javascript and java .can u assign me this

**Comment by simranlotey** [comment]
I assigned you @avinashyadav16

**Comment by simranlotey** [comment]
I assigned you @ashajyothi06

**Comment by DicoderRG** [comment]
Hello,

I would like to work on Typescript

**Comment by DicoderRG** [comment]
and C, C++

**Comment by gh-adithya** [comment]
Hi! I would like to work on this in Python. Could I please be assigned?

**Comment by cjhetzle** [comment]
I'll go ahead with Java FizzBuzz as it's yet to be done. @ashajyothi06 you can continue with JS

**Comment by gh-adithya** [comment]
I have pushed for a PR, please do review. TIA. @simranlotey

**Comment by alriyadsouza** [comment]
I would like to work on it using python. can u please assign me with it.

**Comment by ashajyothi06** [comment]
> I'll go ahead with Java FizzBuzz as it's yet to be done. @ashajyothi06 you can continue with JS

@cjhetzle yeah sure
