### ISSUE TITLE
Convert Celsius to Fahrenheit

### ISSUE THREAD

**Issue by simranlotey** [simranlotey/programs#27]
Write a program to convert a temperature from Celsius to Fahrenheit.

**Comment by AdityaDhavale** [comment]
@simranlotey I would like to work on this issue , will u please assign me?

**Comment by simranlotey** [comment]
Do it @AdityaDhavale

**Comment by AdityaDhavale** [comment]
@simranlotey I've added a program to convert a temperature from Celsius to Fahrenheit in Java . Please check and kindly merge my PR.
