### ISSUE TITLE
Drum Kit (HTML/CSS/JAVASCRIPT)

### ISSUE THREAD

**Issue by aayush105** [simranlotey/programs#318]
[Screencast from 26-10-23 07:22:06 अपराह्न +0545.webm](https://github.com/simranlotey/programs/assets/115408327/a1048950-843d-4a6a-adf3-ad025e644d8c)
This is the sample video of the drum kit where we can click the letter from keyboard that produces the different sound of instruments and we can make a music using those instrument sound.

**Comment by aayush105** [comment]
@simranlotey please review this and assign this to me.

**Comment by simranlotey** [comment]
I assigned you @aayush105

**Comment by ankitkumar0622** [comment]
Hi, can you please assign this task to me.
